### ISSUE TITLE
iubeo.exceptions.ConfigError: Error while parsing value with boolean

### ISSUE THREAD

**Issue by spaceofmiah** [isik-kaplan/iubeo#3]
I get the above error when i run `python manage.py runserver` after configuring **iubeo**. How can i resolve this ?

Although it says None value, is given to DEBUG, but on my environment file, DEBUG is defined.

---
To Replicate this error 
---
Grab project from [repo](https://github.com/spaceofmiah/iubeo-test)

Install dependencies within virtual environment 

Run `python manage.py runserver`

---
Complete Traceback
---

```
Traceback (most recent call last):
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\iubeo\utils.py", line 15, in wrapper
    return f(value)
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\iubeo\casters.py", line 23, in boolean
    raise ValueError('Value "{}" can not be parsed into a boolean.'.format(value))
ValueError: Value "None" can not be parsed into a boolean.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\django\core\management\__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\django\conf\__init__.py", line 82, in __getattr__
    self._setup(name)
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\django\conf\__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\django\conf\__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\miah\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\miah\code\django\test-iubeo\core\settings.py", line 20, in <module>
    DEBUG = CONFIG.DEBUG
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\iubeo\config.py", line 18, in __getattr__
    return raise_config_error_instead(cast)(os.environ.get(var))
  File "C:\Users\miah\code\django\test-iubeo\env\lib\site-packages\iubeo\utils.py", line 17, in wrapper
    raise ConfigError("Error while parsing value with {}".format(f.__name__)) from e
iubeo.exceptions.ConfigError: Error while parsing value with boolean
```

**Comment by isik-kaplan** [comment]
Hello! 

I think there is a tiny misconception happening here, iubeo as of now, does not actually read the values from any config file. It directly tries to read it from the environment. So you'd actually need to export the variables in your .env file for them to be visible to iubeo.

But your issue made me aware of a bug iubeo has right now: 

https://github.com/isik-kaplan/iubeo/blob/591d69585154d394061fc6f5f14fbcf793e0c3ca/iubeo/config.py#L18

Apparently it uses `os.environ.get` to read the variables, which results in that `None` to appear out of nowhere, I'll create a patch version for that. Thank you! 

To fix your issues right now, you can simply source your .env file like below
```py
set -a && source .env && set +a
```
Which automatically exports what you have in that .env file. 

Hope that fixes your issue for now! I'll implement the .env file reading feature as soon as I can! 

Feel free to reopen the issue if the above doesn't fix your problem.

**Comment by spaceofmiah** [comment]
Thanks - probably because i'm on windows ( not sure, but it didn't work ) i couldn't use the below command

```bash
set -a && source .env && set +a
```

so to rectify this i had to do two things 

- i install [python-dotenv](https://pypi.org/project/python-dotenv/) : which sources environment variable 
- i checked up on the iubeo docs again and found out that my variable weren't appropriately configured e.g 


```
# i used (notice the single underscore) 
DATABASE_PORT=xxxx

# instead of 
DATABASE__PORT=xxxx
```

With the above steps, `python manage.py runserver` became successful.

**Comment by isik-kaplan** [comment]
Nice! Glad everything worked out!

Yeah that set and source commands are for linux, I just randomly assumed that you were on linux sorry haha.
